#!/home/pi/.rvm/bin/rvmsudo ruby
# pushbutton for LEDs

leds = [1, 4, 5]
button = 6

require 'wiringpi'
io = WiringPi::GPIO.new
leds.each { |pin| io.mode(pin, OUTPUT) }
io.mode(button, INPUT)

at_exit do
    puts "exiting"
    leds.each { |pin| io.write(pin, LOW) }
end

puts "all set"

while true
    if io.read(button)==HIGH
        leds.each { |pin| io.write(pin, HIGH) }
    else
        leds.each { |pin| io.write(pin, LOW) }
    end
end
